[deps]
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
DFTK = "= 0.2.5"
JLD2 = "0.3"
JSON = "0.21"
MPI = "0.16"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1.5"
