[deps]
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
DFTK = "= 0.2.7, 0.3"
JLD2 = "0.3, 0.4"
JSON3 = "1"
MPI = "0.16, 0.17, 0.18, 0.19"
PackageCompiler = "1"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1.5"
